[package]
name = "atlas-scheduler"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
tokio.workspace = true

atlas-discovery = { path = "../atlas-discovery" }
atlas-jobs = { path = "../atlas-jobs" }
atlas-snapshot = { path = "../atlas-snapshot" }
atlas-store = { path = "../atlas-store" }